### ISSUE TITLE
__NEXT_REDUX_WRAPPER_HYDRATE__ cookie bug

### ISSUE THREAD

**Issue by zhangwei900808** [bjoluc/next-redux-cookie-wrapper#28] opened 2022-01-19 12:35 UTC
website eg:www.example.com
users：User A and User B
action：User A login example website and can get cookie，then User B with other PC open browser run example website User A login info appear in User B browser!!!
![image](https://user-images.githubusercontent.com/4385154/150131255-f2bf9692-77b1-4a79-bf9f-bf2ee8dfb708.png)

**Comment by zhangwei900808** [comment] 2022-01-19 12:35
User B login info must null why B got User A login info???

**Comment by zhangwei900808** [comment] 2022-01-19 12:39
store.js
```
export const initStore = configureStore({
  reducer: combinedReducers,
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().prepend(
    nextReduxCookieMiddleware({
      // 是否压缩
      // compress: false,
      subtrees: ["auth.accessToken", "auth.refreshToken", "auth.isLogin", "auth.me"],
    })
  ).concat(logger)
})
```

authSlice.js
```
// 初始化数据
const internalInitialState = {
  accessToken: null,
  refreshToken: null,
  me: null,
  errorMsg: null,
  isLogin: false,
  isExpired: false
};

// reducer
export const authSlice = createSlice({
  name: 'auth',
  initialState: internalInitialState,
  reducers: {
    updateAuth(state, action) {
      state.accessToken = action.payload.accessToken;
      state.me = action.payload.me;
    },
    reset: () => internalInitialState,
    setExpired(state, action) {
      state.isExpired = action.payload;
    },
    getRefreshToken(state, action) {
      return state.refreshToken;
    },
    setAuth(state, action) {
      console.log('-----------setAuth-----------', action)
      if (action.payload) {
        state.accessToken = action.payload.accessToken;
        state.refreshToken = action.payload.refreshToken;
        state.isLogin = action.payload.isLogin;
        state.isExpired = action.payload.isExpired;
      }
    }
  },
  extraReducers: {
    // 水合，拿到服务器端的reducer注入到客户端的reducer，达到数据统一的目的
    [HYDRATE]: (state, action) => {
      console.log('-------------------------------------------------------')
      console.log('----------------------AUTH HYDRATE---------------------')
      console.log('-------------------------------------------------------')
      // console.log('HYDRATE', state, action.payload);
      return {
        ...state,
        ...action.payload.auth,
      };
    },
```

**Comment by zhangwei900808** [comment] 2022-01-19 13:17
@bjoluc I found the reason and recurrent
![image](https://user-images.githubusercontent.com/4385154/150138081-47824ccc-bee3-4177-a10e-3afd03baf7f3.png)
when I remove User B cookie and refresh User A(user A had login ) chrome is appear!!!
but When dont remove User B its worked!!!

**Comment by bjoluc** [comment] 2022-01-19 22:25
Hi @zhangwei900808,
I'm not sure if I fully get your issue. To me, it sounds like two browser instances on your machine share cookies. Anyway, any behavior across browser tabs is up to your browser or application and not next-redux-cookie-wrapper. I'm going to close this as unrelated. Anyway, best of success resolving it!

**Closed by bjoluc** 2022-01-19 22:25 UTC
Labels: question

**Comment by zhangwei900808** [comment] 2022-01-20 12:31
@bjoluc you dont understand 
1、is not share cookie
2、is next-redux-cookie-wrapper bug

eg: 
User A in Beijing and User B in Shanghai
when User A open website and login then next-redux-cookie-wrapper set cookie in chrome
when User B open website not login but he got User A cookie  in him chrome

so Why appear it???

**Comment by bjoluc** [comment] 2022-01-20 13:05
I tend to be very careful myself about calling out bugs in libraries without putting together a minimal reproducible example, and I'm afraid I can't help you without a self-contained repro repository. Get active and track down the cause of the problem, and when you know which component/library causes it, please come back here with a minimal repro repo and I'll be happy to investigate further. You may also take a look [here](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).

**Comment by zhangwei900808** [comment] 2022-01-20 14:09
![image](https://user-images.githubusercontent.com/4385154/150354370-9a8a20e0-65eb-4314-a6b8-160fca026600.png)
@bjoluc

**Comment by zhangwei900808** [comment] 2022-01-20 14:25
![image](https://user-images.githubusercontent.com/4385154/150357106-de070fa7-e558-4da1-bb24-dc78034b6d06.png)

**Comment by zhangwei900808** [comment] 2022-01-20 14:29
![image](https://user-images.githubusercontent.com/4385154/150357740-dc76163c-4c21-4936-b4e6-c06128bd27e0.png)
@bjoluc

**Comment by zhangwei900808** [comment] 2022-01-22 12:01
[redux-toolkit-cookie-wrapper-bug](https://github.com/zhangwei900808/redux-toolkit-cookie-wrapper-bug)
@bjoluc You take a look

**Comment by zhangwei900808** [comment] 2022-01-22 12:16
![image](https://user-images.githubusercontent.com/4385154/150638153-c757f78c-aa86-4e36-84e7-f6223ff130f5.png)
@bjoluc

**Comment by bjoluc** [comment] 2022-01-23 19:53
Thanks for the repro @zhangwei900808. Your problem is unrelated and took some time for me to spot: The behavior you are facing is due to a single shared store instance on the server due to a faulty `initStore` definition. In your repro you write

```js
export const initStore = configureStore({...});
export const store = wrapMakeStore(() => initStore);
export const wrapper = createWrapper(store, {...});
```
which should be something along these lines:
```js
const makeStore = () => configureStore({...});
const wrappedMakeStore = wrapMakeStore(makeStore);
export const wrapper = createWrapper(wrappedMakeStore, {...});
```
or simply as in [the demo](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/8d17ae09d5eda83647fc0fae89a8663867a1a4f7/demo/store.ts#L45-L71):
```js
const makeStore = wrapMakeStore(() => configureStore({...}));
export const wrapper = createWrapper(makeStore, {...});
```

Cheers!

**Comment by zhangwei900808** [comment] 2022-01-26 12:48
when I used below code is have a problem is not got refresh token ,tips me is null!
```
import axios from 'axios';
import createAuthRefreshInterceptor from "axios-auth-refresh";
import {refreshToken} from '@/store/slices/authSlice'
import {initStore} from '@/store'

const axiosInstance = axios.create({
  baseURL: `${process.env.NEXT_PUBLIC_API_HOST}`,
  withCredentials: false,
});

// refresh token when 401
createAuthRefreshInterceptor(axiosInstance, async failedRequest => {
  const {dispatch} = initStore();
  const res = await dispatch(refreshToken());
  console.log('============createAuthRefreshInterceptor callback=======', res.payload)
  if (res.payload && res.payload.accessToken)
    failedRequest.response.config.headers.Authorization = 'Bearer ' + res.payload.accessToken;
  return Promise.resolve();
});

export default axiosInstance;

```


```
export const refreshToken = createAsyncThunk('auth/refreshToken', async (params, thunkAPI) => {
  try {
    const {refreshToken} = thunkAPI.getState().auth;
    if (refreshToken) {
      console.log('==== refreshToken ====', refreshToken)
      const response = await axios.post('/auth/oauth/token', qs.stringify({
        grant_type: 'refresh_token',
        refresh_token: refreshToken
      }));
      const resdata = response.data;
      console.log('====refreshToken resdata ====', resdata)
      if (resdata.access_token) {
        // const refetch = await axios.get('/account/me', {
        //   headers: {Authorization: `Bearer ${resdata.access_token}`},
        // });
        // console.log('====refreshToken return1 ====', resdata)

        return {
          accessToken: resdata.access_token,
          refreshToken: resdata.refresh_token,
          isLogin: true,
          isExpired: false,
          // me: {
          //   name: refetch.data.name,
          //   avatar: refetch.data.avatar
          // }
        };
      } else {
        return thunkAPI.rejectWithValue({errorMsg: response.data.message});
      }
    } else {
      return thunkAPI.rejectWithValue({errorMsg: "no refreshToken"});
    }
  } catch (error) {
    return thunkAPI.rejectWithValue({errorMsg: error.message});
  }
});
```

**Comment by zhangwei900808** [comment] 2022-01-28 07:59
I created a mine middle and set axios 401 methods , Its Worked!
```
export const initStore = () => configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().prepend(
    nextReduxCookieMiddleware({
      // 是否压缩
      // compress: false,
      subtrees: ["auth.accessToken", "auth.refreshToken", "auth.isLogin", "auth.me"],
    })
  ).concat((store) => (next) => (action) => {
    // refresh token when 401
    createAuthRefreshInterceptor(axiosInstance, async failedRequest => {
      const res = await store.dispatch(refreshToken());
      console.log('============createAuthRefreshInterceptor callback=======', res.payload)
      if (res.payload && res.payload.accessToken)
        failedRequest.response.config.headers.Authorization = 'Bearer ' + res.payload.accessToken;
      return Promise.resolve();
    });
    //自定义中间件作用：如果上面的判断不返回则会报错，所以返回了一个空的自定义中间件
    return next(action);
  }).concat(process.env.NODE_ENV === `development` ? logger : (store) => (next) => (action) => {
    //自定义中间件作用：如果上面的判断不返回则会报错，所以返回了一个空的自定义中间件
    return next(action);
  })
})
```
